---
### BLE driver dependencies
- name: ble_tag_monitor | apt install
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - libbluetooth3
    - bluez # for hciconfig (also in blobs) TODO get rid of this
    - python-bluez
  sudo_user: root
- name: install the lescan tool
  copy: src=lescan.py dest=/usr/local/bin/lescan
      owner=root group=root mode=0755
  sudo_user: root
# TODO: move the lescan.py to -drivers

- name: mkdir ~/drivers_ENVs
  file: path={{ home }}/drivers_ENVs state=directory

- name: extract the drivers names
  shell: >
      {{ app }}/config.py | jq --raw-output '.loaded_drivers|.[]'
  register: driver_names

- name: create and update the drivers virtualenvs
  pip: virtualenv={{ home }}/drivers_ENVs/{{ item }} name=pip state=latest
  with_items: driver_names.stdout_lines
- name: install drivers requirements.txt
  pip: virtualenv={{ home }}/drivers_ENVs/{{ item }}
      requirements={{ drivers }}/drivers/{{ item }}/requirements.txt
      extra_args="--use-wheel --find-links={{ drivers }}/wheelhouse"
  with_items: driver_names.stdout_lines
  ignore_errors: True

# TODO: delete the virtualenvs not in use

### Open-zwave dependencies

