- hosts: localhost
  gather_facts: True
  vars_files:
    - "repo_overrides.yml"
  vars:
    pulling: True
  roles:
    - hub-pull

- hosts: localhost
  gather_facts: True
  sudo_user: smarthome
  sudo: yes
  vars_files:
    - "repo_overrides.yml"
  roles:
    - hub
