- hosts: localhost
  gather_facts: True
  tasks:
    - copy: 'dest="../repo_overrides.yml" force=no content="EMPTY: --"'

- hosts: localhost
  gather_facts: True
  vars_files:
    - ["NOT_EXISTING_HACK", "../repo_overrides.yml"]
  vars:
    pulling: True
  roles:
    - hub-pull

- hosts: localhost
  gather_facts: True
  sudo_user: smarthome
  sudo: yes
  vars_files:
    - ["NOT_EXISTING_HACK", "../repo_overrides.yml"]
  roles:
    - hub
