- hosts: localhost
  gather_facts: True
  sudo_user: smarthome
  sudo: yes
  roles:
    - hub

- hosts: localhost
  gather_facts: True
  roles:
    - hub-pull

- hosts: localhost
  vars:
    - home: "/home/{{ ansible_user_id }}"
    - logfile: "{{ home }}/ansible-pull.log"
  tasks:
    # If the pull was successful, clear the log
    - file: path={{ logfile }} state=absent
