- hosts: raspberrypi
  gather_facts: False
  remote_user: pi
  sudo: yes
  tasks:
    - user: name=smarthome
    - name: add smarthome-services to authorized_key
      authorized_key: user=pi
        key="{{ lookup('file', 'keys/smarthome-services.pub') }}"
    - user: name=pi password=!

- hosts: raspberrypi
  gather_facts: True
  remote_user: pi
  sudo_user: smarthome
  sudo: yes
  roles:
    - hub

- hosts: raspberrypi
  gather_facts: True
  remote_user: pi
  roles:
    - hub-pull
