- hosts: tag_smarthome_hub
  gather_facts: False
  remote_user: admin
  sudo: yes
  tasks:
    - user: name=smarthome
    - name: add smarthome-services to authorized_key
      authorized_key: user=admin
        key="{{ lookup('file', 'keys/smarthome-services.pub') }}"
    - user: name=admin password=!

- hosts: tag_smarthome_hub
  gather_facts: True
  remote_user: admin
  sudo_user: smarthome
  sudo: yes
  roles:
    - hub

- hosts: tag_smarthome_hub
  gather_facts: True
  remote_user: admin
  roles:
    - hub-pull
