---
home: "/home/{{ ansible_user_id }}"

deploy: "{{ home }}/smarthome-deployment"
blobs: "{{ home }}/smarthome-deployment-blobs"

logfile: "{{ home }}/ansible-pull.log" # TODO

deploy_repo: "git@github.com:smart-home/smarthome-deployment.git"
deploy_rev: "master"
blobs_repo: "git@github.com:smart-home/smarthome-deployment-blobs.git"
blobs_rev: "master"
