# Playbook to provision a micro EC2 instance and deploy the hub on it

# To use it, first `pip install boto`,
# set EC2_REGION, AWS_ACCESS_KEY and AWS_SECRET_KEY env variables
# and then run it as:
# `ansible-playbook -i inventory.ini playbook.yml \
# --extra-vars "keypair_name=marvin_rsa security_group=Relax"`

- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_type: "t1.micro"
    image: "ami-d3675dba" # Debian Wheezy 7.4 PVM x86_64
    region: "us-east-1"
  tasks:
    - name: make one instance
      ec2: image={{ image }}
           instance_type={{ instance_type }}
           region={{ region }}
           key_name={{ keypair_name }}
           group={{ security_group }}
           wait=true
      register: ec2_info

    - add_host: hostname={{ item.public_dns_name }} groupname=hub_ec2_hosts
      with_items: ec2_info.instances

    - name: wait for instances to listen on port:22
      wait_for:
        state=started
        host={{ item.public_dns_name }}
        port=22
      with_items: ec2_info.instances

    - name: cache the ec2 node host key
      local_action: shell ssh-keyscan -H {{ item.public_dns_name }} >> ~/.ssh/known_hosts
      with_items: ec2_info.instances

- hosts: hub_ec2_hosts
  gather_facts: True
  remote_user: admin
  vars:
    tmp_dir: "/tmp/smarthome-hub-sync-deploy/"
  tasks:
    - name: install rsync on the remote machin
      apt: pkg=rsync update_cache=yes
      sudo: yes

    - name: checkout the hub repo
      local_action: git dest={{ tmp_dir }}
          repo=git@github.com:smart-home/smarthome-hub-sync.git

    - name: upload the hub code to the node
      synchronize: src={{ tmp_dir }} dest=/home/admin/smarthome-hub-sync/

    # TODO: make this a decent playbook
    - command: /home/admin/smarthome-hub-sync/smarthome-hub-setup.sh
