# To use it, first `pip install boto`,
# set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY env variables
# (NOTE! env vars differ from the new_ec2.yml script)
# and then run it as:
# `ansible-playbook -i ec2.py update_ec2.yml`

- hosts: tag_smarthome_hub
  gather_facts: True
  remote_user: admin
  vars:
    tmp_dir: "/tmp/smarthome-hub-deploy"
    home: "/home/admin"
    app: "{{ home }}/smarthome-hub-sync"
    config: "{{ home }}/smart-home-config"
  tasks:
    - include: main.yml
